// SWIP-09 — nextBestAction state ladder. The orchestration hint must be an explicit,
// top-down ladder where EVERY state — including the terminal "clean run + assets generated
// → qa_report" — is reachable. Before the fix, the qa_generate branch keyed on
// recordedActions.length > 0, which was always true by that point, so the terminal
// qa_report recommendation could never fire. Table-driven over synthetic sessions.

import { describe, expect, it } from 'vitest';
import { nextBestAction } from '../src/tools/agent.js';
import type { JobRecord, Session } from '../src/session/store.js';

function makeSession(over: Partial<Session> = {}): Session {
  const base: Partial<Session> = {
    id: 's-test',
    root: '/tmp/project',
    dir: '/tmp/project/.swipium',
    createdAt: Date.now(),
    envChanges: [],
    workarounds: [],
    mode: 'structured' as Session['mode'],
    responseMode: 'normal' as Session['responseMode'],
    sensitive: false,
    budget: { maxMinutes: 8, maxActions: 20, maxScreenshots: 8, maxSnapshotFailures: 3, maxNoChangeActions: 3 },
    counters: { actions: 0, screenshots: 0, snapshotFailures: 0, noChangeActions: 0 },
    screenshotCount: 0,
    jobs: new Map<string, JobRecord>(),
    artifacts: [],
    findings: [],
    notes: [],
    mutations: [],
    recordedActions: [],
    fixtures: [],
    auth: {},
    milestones: {},
    secrets: new Set<string>(),
    inputs: [],
    generatedValues: [],
    inputValues: new Map<string, string>(),
    aborts: new Map<string, AbortController>(),
  };
  return { ...base, ...over } as Session;
}

function job(status: JobRecord['status'], startedAt = 1): JobRecord {
  return { jobId: `job-${status}-${startedAt}`, kind: 'test_this', status, startedAt };
}

const tap = { at: 1, action: 'tap', selector: 'Log in', selectorKind: 'text' as const };
const finding = { at: 1, severity: 'high', kind: 'crash', detail: 'app crashed' };

describe('nextBestAction state ladder (SWIP-09)', () => {
  const cases: Array<{ name: string; session: Session; goal?: string; tool: string }> = [
    {
      name: '1. running job → qa_job_status (even with device/app bound)',
      session: makeSession({
        device: 'emulator-5554',
        appId: 'com.example.app',
        jobs: new Map([['j1', job('running')]]),
        recordedActions: [tap],
      }),
      tool: 'qa_job_status',
    },
    {
      name: '2. no device → qa_test_this',
      session: makeSession(),
      tool: 'qa_test_this',
    },
    {
      name: '2. no device, finished job does not block setup → qa_test_this',
      session: makeSession({ jobs: new Map([['j1', job('done')]]) }),
      tool: 'qa_test_this',
    },
    {
      name: '3. device but no app → qa_prepare_target',
      session: makeSession({ device: 'emulator-5554' }),
      tool: 'qa_prepare_target',
    },
    {
      name: '4. app up, nothing exercised → qa_smoke',
      session: makeSession({ device: 'emulator-5554', appId: 'com.example.app' }),
      tool: 'qa_smoke',
    },
    {
      name: '5. findings recorded → qa_report',
      session: makeSession({ device: 'emulator-5554', appId: 'com.example.app', recordedActions: [tap], findings: [finding] }),
      tool: 'qa_report',
    },
    {
      name: '6. clean run, actions recorded, no assets yet → qa_generate',
      session: makeSession({ device: 'emulator-5554', appId: 'com.example.app', recordedActions: [tap] }),
      tool: 'qa_generate',
    },
    {
      name: '6. unrelated workarounds do not count as generated assets → qa_generate',
      session: makeSession({
        device: 'emulator-5554',
        appId: 'com.example.app',
        recordedActions: [tap],
        workarounds: ['built device-specific APK set via bundletool + installed'],
      }),
      tool: 'qa_generate',
    },
    {
      name: '7. terminal: suite generated by the qa_test_this pipeline → qa_report',
      session: makeSession({
        device: 'emulator-5554',
        appId: 'com.example.app',
        recordedActions: [tap],
        workarounds: ['generated a POM suite (2 runnable flow(s))'],
      }),
      tool: 'qa_report',
    },
    {
      name: '7. terminal: assets generated via qa_generate → qa_report',
      session: makeSession({
        device: 'emulator-5554',
        appId: 'com.example.app',
        recordedActions: [tap],
        workarounds: ['generated flow test asset(s) from recorded actions (qa_generate)'],
      }),
      tool: 'qa_report',
    },
  ];

  it.each(cases)('$name', ({ session, goal, tool }) => {
    const next = nextBestAction(session, goal);
    expect(next.tool).toBe(tool);
    expect(next.why.length).toBeGreaterThan(0);
    expect(next.args.sessionId).toBe(session.id);
  });

  it('covers every ladder state — the terminal qa_report is reachable', () => {
    const tools = new Set(cases.map((c) => c.tool));
    expect([...tools].sort()).toEqual(['qa_generate', 'qa_job_status', 'qa_prepare_target', 'qa_report', 'qa_smoke', 'qa_test_this']);
    // Terminal state specifically: no findings, assets generated → wrap up with qa_report.
    const terminal = nextBestAction(
      makeSession({
        device: 'emulator-5554',
        appId: 'com.example.app',
        recordedActions: [tap],
        workarounds: ['generated a POM suite (1 runnable flow(s))'],
      }),
    );
    expect(terminal).toMatchObject({ tool: 'qa_report' });
    expect(terminal.why).toMatch(/wrap up/);
  });

  it('threads the goal into the setup recommendation', () => {
    const next = nextBestAction(makeSession(), 'test_login');
    expect(next.tool).toBe('qa_test_this');
    expect(next.args.goal).toBe('test_login');
    expect(next.why).toContain('test_login');
  });

  it('points polling at the most recent job', () => {
    const s = makeSession({
      device: 'emulator-5554',
      jobs: new Map([
        ['old', job('done', 1)],
        ['new', job('running', 2)],
      ]),
    });
    const next = nextBestAction(s);
    expect(next.tool).toBe('qa_job_status');
    expect(next.args.jobId).toBe('job-running-2');
  });
});
