// SWIPIUM-REQ-04 — CI example emitter. Pure: produces a LOCAL-Appium CI template (GitHub Actions)
// for the generated JS or Python suite. Per the non-goals, this is a starting example only (no cloud
// device-farm config), and the tool writes it as `ci.example.yml` — never an active workflow.

import type { AutomationLanguage } from './projectProfile.js';

export function emitCiExample(language: AutomationLanguage, _opts: { appId?: string } = {}): string {
  if (language === 'python') return pythonCi();
  return jsCi(language);
}

function jsCi(language: AutomationLanguage): string {
  const installTs = language === 'typescript' ? '' : '';
  return `# Generated by Swipium — EXAMPLE local-Appium CI (rename to .github/workflows/*.yml to enable).
# Local Appium + Android emulator only. No cloud device farm (out of scope for v1).
name: appium-e2e (example)
on:
  workflow_dispatch: {}
jobs:
  android-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm install${installTs}
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules && sudo udevadm trigger --name-match=kvm
      - name: Run Appium e2e on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          script: |
            npx appium &
            sleep 8
            ANDROID_APP_PACKAGE=\${{ env.ANDROID_APP_PACKAGE }} npm test
        env:
          # Provide secrets via repo/Org secrets — never commit them.
          SWIPIUM_TEST_PASSWORD: \${{ secrets.SWIPIUM_TEST_PASSWORD }}
`;
}

function pythonCi(): string {
  return `# Generated by Swipium — EXAMPLE local-Appium CI (rename to .github/workflows/*.yml to enable).
# Local Appium + Android emulator only. No cloud device farm (out of scope for v1).
name: appium-e2e (example)
on:
  workflow_dispatch: {}
jobs:
  android-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          pip install -r requirements.txt
          npm install -g appium
          appium driver install uiautomator2
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules && sudo udevadm trigger --name-match=kvm
      - name: Run Appium e2e on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          script: |
            appium &
            sleep 8
            ANDROID_APP_PACKAGE=\${{ env.ANDROID_APP_PACKAGE }} pytest
        env:
          SWIPIUM_TEST_PASSWORD: \${{ secrets.SWIPIUM_TEST_PASSWORD }}
`;
}
