// SWIPIUM-REQ-04 — JS/TS WebdriverIO + Appium emitter. Pure: turns the shared Appium model into a
// runnable WebdriverIO POM suite (page/screen classes with locator getters + action methods, env-
// driven capabilities, structured waits). No XPath is ever emitted; coordinate fallbacks are marked
// non-release-grade. Aligns with the Appium JS quickstart (WebdriverIO) locator-strategy guidance.

import type { GeneratedFile } from '../suite/pom.js';
import type { AppiumLocator, AppiumScreen, AppiumStep, AppiumSuiteModel, CrossPlatformElement } from './appiumModel.js';
import type { AutomationProjectProfile } from './projectProfile.js';

export interface JsEmitInput {
  model: AppiumSuiteModel;
  profile: AutomationProjectProfile;
  appId?: string;
  language: 'typescript' | 'javascript';
}

const DEFAULT_TIMEOUT = 15000;

function pascal(s: string): string {
  const parts = s
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  return parts.map((p) => p[0].toUpperCase() + p.slice(1)).join('') || 'X';
}

/** Env var (SWIPIUM_TEST_PASSWORD) → a stable testData key (password). */
export function varToKey(v: string): string {
  const stripped = v.replace(/^SWIPIUM_(TEST_)?/i, '');
  const parts = stripped
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean);
  if (!parts.length) return 'value';
  return parts.map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('');
}

/** wdio selector string for a single Appium locator (no XPath, ever). */
export function wdioSelector(loc: AppiumLocator): string {
  switch (loc.strategy) {
    case 'accessibilityId':
      return `~${loc.value}`;
    case 'id':
      return `id=${loc.value}`;
    case 'androidUiautomator':
      return `android=new UiSelector().text(${JSON.stringify(loc.value)})`;
    case 'name':
      return `-ios predicate string:name == ${JSON.stringify(loc.value)} OR label == ${JSON.stringify(loc.value)}`;
    case 'iosPredicate':
      return `-ios predicate string:${loc.value}`;
    case 'iosClassChain':
      return `-ios class chain:${loc.value}`;
    case 'coordinate':
      return '';
    default:
      return '';
  }
}

function platformLocatorLiteral(el: CrossPlatformElement): string {
  const parts: string[] = [];
  if (el.android) parts.push(`android: ${JSON.stringify(wdioSelector(el.android))}`);
  if (el.ios) parts.push(`ios: ${JSON.stringify(wdioSelector(el.ios))}`);
  if (el.fallback && el.fallback.strategy === 'coordinate') parts.push(`coordinate: ${JSON.stringify(el.fallback.value)}`);
  else if (el.fallback && !el.android && !el.ios) parts.push(`android: ${JSON.stringify(wdioSelector(el.fallback))}`);
  return `{ ${parts.join(', ')} }`;
}

export function emitJsSuite(input: JsEmitInput): GeneratedFile[] {
  const ts = input.language === 'typescript';
  const ext = ts ? 'ts' : 'js';
  const t = (annotation: string) => (ts ? annotation : '');
  const files: GeneratedFile[] = [];

  files.push({ path: 'package.json', content: packageJson(input) });
  if (ts) files.push({ path: 'tsconfig.json', content: tsconfigJson() });
  files.push({ path: `wdio.conf.${ext}`, content: wdioConf(ts, ext) });
  files.push({ path: `src/config/capabilities.${ext}`, content: capabilities(input, ts) });
  files.push({ path: `src/utils/locators.${ext}`, content: locatorsUtil(ts) });
  files.push({ path: `src/utils/waits.${ext}`, content: waitsUtil(ts) });
  files.push({ path: `src/screens/BaseScreen.${ext}`, content: baseScreen(ts) });
  for (const screen of input.model.screens) {
    files.push({ path: `src/screens/${screen.className}.${ext}`, content: screenClass(screen, input.model.steps, ts, t) });
  }
  files.push({ path: `src/data/testData.${ext}`, content: testData(input.model, ts) });
  files.push({ path: `test/smoke.e2e.${ext}`, content: smokeTest(input.model, ts) });
  return files;
}

function packageJson(input: JsEmitInput): string {
  const ts = input.language === 'typescript';
  const name = `${(input.appId ?? 'app').split('.').pop()}-appium-suite`;
  const pkg: Record<string, unknown> = {
    name,
    private: true,
    type: 'module',
    description: 'Generated by Swipium — WebdriverIO + Appium POM suite (review before committing).',
    scripts: {
      test: 'wdio run ./wdio.conf.' + (ts ? 'ts' : 'js'),
    },
    devDependencies: {
      '@wdio/cli': '^9.0.0',
      '@wdio/local-runner': '^9.0.0',
      '@wdio/mocha-framework': '^9.0.0',
      '@wdio/appium-service': '^9.0.0',
      '@wdio/spec-reporter': '^9.0.0',
      appium: '^2.11.0',
      ...(ts ? { typescript: '^5.7.0', tsx: '^4.19.0', '@types/node': '^22.0.0' } : {}),
    },
  };
  return JSON.stringify(pkg, null, 2) + '\n';
}

function tsconfigJson(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'NodeNext',
          moduleResolution: 'NodeNext',
          types: ['node', '@wdio/globals/types', '@wdio/mocha-framework'],
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
        },
        include: ['src/**/*.ts', 'test/**/*.ts', 'wdio.conf.ts'],
      },
      null,
      2,
    ) + '\n'
  );
}

function wdioConf(ts: boolean, ext: string): string {
  const header = '// Generated by Swipium. WebdriverIO + Appium config — capabilities come from env (see src/config/capabilities).';
  const importLine = `import { buildCapabilities } from './src/config/capabilities.js';`;
  const typeAnno = ts ? `\nimport type { Options } from '@wdio/types';\n` : '\n';
  const cfgType = ts ? ': WebdriverIO.Config' : '';
  return `${header}${typeAnno}${importLine}

export const config${cfgType} = {
  runner: 'local',
  hostname: process.env.APPIUM_HOST || '127.0.0.1',
  port: Number(process.env.APPIUM_PORT || 4723),
  path: '/',
  specs: ['./test/**/*.e2e.${ext}'],
  maxInstances: 1,
  capabilities: [buildCapabilities()],
  logLevel: 'info',
  waitforTimeout: ${DEFAULT_TIMEOUT},
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: { ui: 'bdd', timeout: 120000 },
  services: [['appium', { args: { address: process.env.APPIUM_HOST || '127.0.0.1' } }]],
};
`;
}

function capabilities(input: JsEmitInput, ts: boolean): string {
  const android = input.model.platforms.android;
  const ret = ts ? ': WebdriverIO.Capabilities' : '';
  const appId = input.appId ?? '';
  const lines: string[] = [];
  lines.push('// Generated by Swipium. ALL device/app config is environment-driven — no secrets, no hardcoded paths.');
  lines.push('// Android is the default fast-feedback backend; set SWIPIUM_PLATFORM=ios to target iOS (XCUITest).');
  lines.push('');
  lines.push(`export function buildCapabilities()${ret} {`);
  lines.push(`  const platform = (process.env.SWIPIUM_PLATFORM || ${JSON.stringify(android ? 'android' : 'ios')}).toLowerCase();`);
  lines.push("  if (platform === 'ios') {");
  lines.push('    return {');
  lines.push("      platformName: 'iOS',");
  lines.push("      'appium:automationName': 'XCUITest',");
  lines.push("      'appium:deviceName': process.env.IOS_DEVICE_NAME || 'iPhone 15',");
  lines.push("      'appium:platformVersion': process.env.IOS_PLATFORM_VERSION,");
  lines.push(`      'appium:bundleId': process.env.IOS_BUNDLE_ID${appId ? ` || ${JSON.stringify(appId)}` : ''},`);
  lines.push("      'appium:app': process.env.IOS_APP_PATH,");
  lines.push("      'appium:udid': process.env.IOS_UDID,");
  lines.push("      'appium:noReset': process.env.SWIPIUM_NO_RESET === 'true',");
  lines.push('    };');
  lines.push('  }');
  lines.push('  // Android UiAutomator2 (default).');
  lines.push('  return {');
  lines.push("    platformName: 'Android',");
  lines.push("    'appium:automationName': 'UiAutomator2',");
  lines.push("    'appium:deviceName': process.env.ANDROID_DEVICE_NAME || 'Android Emulator',");
  lines.push(`    'appium:appPackage': process.env.ANDROID_APP_PACKAGE${appId ? ` || ${JSON.stringify(appId)}` : ''},`);
  lines.push("    'appium:appActivity': process.env.ANDROID_APP_ACTIVITY,");
  lines.push("    'appium:app': process.env.ANDROID_APP_PATH,");
  lines.push("    'appium:udid': process.env.ANDROID_UDID,");
  lines.push("    'appium:noReset': process.env.SWIPIUM_NO_RESET === 'true',");
  lines.push('  };');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function locatorsUtil(ts: boolean): string {
  const typeBlock = ts
    ? `export interface PlatformLocator {\n  android?: string;\n  ios?: string;\n  /** "x,y" coordinate fallback — non-release-grade. */\n  coordinate?: string;\n}\n\n`
    : '';
  const param = ts ? 'loc: PlatformLocator' : 'loc';
  const ret = ts ? ': string' : '';
  return `// Generated by Swipium. Resolves a centralized cross-platform locator to a wdio selector at runtime.
${typeBlock}export function resolveSelector(${param})${ret} {
  // @ts-ignore wdio global
  const android = typeof driver !== 'undefined' ? driver.isAndroid : true;
  const selector = android ? loc.android : loc.ios;
  if (!selector) {
    throw new Error('No durable selector for this platform — element relies on a coordinate fallback (non-release-grade). Add an accessibility id / resource-id / testID.');
  }
  return selector;
}

export function coordinateOf(${param})${ts ? ': [number, number] | undefined' : ''} {
  if (!loc.coordinate) return undefined;
  const [x, y] = loc.coordinate.split(',').map(Number);
  return [x, y];
}
`;
}

function waitsUtil(ts: boolean): string {
  const elAnno = ts ? ': WebdriverIO.Element' : '';
  const numAnno = ts ? ': number' : '';
  return `// Generated by Swipium. Structured waits — never a bare sleep. Auto-wait before interaction
// (Playwright-style resilience, applied to mobile Appium).
export const DEFAULT_TIMEOUT = ${DEFAULT_TIMEOUT};

export async function waitVisible(el${elAnno}, timeout${numAnno} = DEFAULT_TIMEOUT) {
  await el.waitForDisplayed({ timeout });
  return el;
}

export async function waitEnabled(el${elAnno}, timeout${numAnno} = DEFAULT_TIMEOUT) {
  await el.waitForEnabled({ timeout });
  return el;
}
`;
}

function baseScreen(ts: boolean): string {
  const locImport = ts ? `import type { PlatformLocator } from '../utils/locators.js';\n` : '';
  const p = (name: string, type: string) => (ts ? `${name}: ${type}` : name);
  return `// Generated by Swipium. BaseScreen centralizes all element interaction so selectors are
// resolved per-platform in ONE place and tests never touch raw selectors.
${locImport}import { resolveSelector, coordinateOf } from '../utils/locators.js';
import { waitVisible, waitEnabled, DEFAULT_TIMEOUT } from '../utils/waits.js';

export class BaseScreen {
  protected async element(${p('loc', 'PlatformLocator')}) {
    // @ts-ignore wdio global
    return $(resolveSelector(loc));
  }

  protected async tap(${p('loc', 'PlatformLocator')}) {
    const el = await this.element(loc);
    await waitEnabled(await waitVisible(el));
    await el.click();
  }

  protected async type(${p('loc', 'PlatformLocator')}, ${p('value', 'string')}) {
    const el = await this.element(loc);
    await waitVisible(el);
    await el.setValue(value);
  }

  protected async scrollTo(${p('loc', 'PlatformLocator')}) {
    const el = await this.element(loc);
    await el.scrollIntoView();
    await waitVisible(el);
  }

  protected async isVisible(${p('loc', 'PlatformLocator')})${ts ? ': Promise<boolean>' : ''} {
    const el = await this.element(loc);
    return el.isDisplayed();
  }

  async assertVisible(${p('loc', 'PlatformLocator')}) {
    const el = await this.element(loc);
    await waitVisible(el);
  }

  async assertTextVisible(${p('text', 'string')}) {
    // Non-release-grade text/OCR assertion — prefer a structured locator.
    // @ts-ignore wdio global
    const el = await $('android=new UiSelector().textContains(' + JSON.stringify(text) + ')');
    await waitVisible(el);
  }

  // Coordinate tap — brittle, non-release-grade fallback. Only used when no durable locator exists.
  async tapAt(${p('x', 'number')}, ${p('y', 'number')}) {
    // @ts-ignore wdio global
    await driver.action('pointer')
      .move({ x, y }).down().pause(50).up().perform();
  }

  async pressKey(${p('key', 'string')}) {
    // @ts-ignore wdio global
    if (driver.isAndroid && key === 'back') { await driver.back(); return; }
    // @ts-ignore wdio global
    await driver.keys([key]);
  }

  async swipe(${p('direction', 'string')}) {
    // @ts-ignore wdio global
    const { width, height } = await driver.getWindowSize();
    const cx = Math.round(width / 2), cy = Math.round(height / 2);
    const map = {
      up: [cx, Math.round(height * 0.8), cx, Math.round(height * 0.2)],
      down: [cx, Math.round(height * 0.2), cx, Math.round(height * 0.8)],
      left: [Math.round(width * 0.8), cy, Math.round(width * 0.2), cy],
      right: [Math.round(width * 0.2), cy, Math.round(width * 0.8), cy],
    };
    const [x1, y1, x2, y2] = map[${ts ? 'direction as keyof typeof map' : 'direction'}] || map.up;
    // @ts-ignore wdio global
    await driver.action('pointer')
      .move({ x: x1, y: y1 }).down().pause(100).move({ duration: 600, x: x2, y: y2 }).up().perform();
  }

  async openUrl(${p('url', 'string')}) {
    // @ts-ignore wdio global
    await driver.url(url);
  }
}
`;
}

/** Per-screen action method name for an (element, action) pair. */
function methodName(action: AppiumStep['action'], element: string): string {
  const E = pascal(element);
  switch (action) {
    case 'tap':
      return `tap${E}`;
    case 'inputText':
      return `enter${E}`;
    case 'scrollTo':
      return `scrollTo${E}`;
    case 'assertVisible':
      return `assert${E}Visible`;
    default:
      return `act${E}`;
  }
}

function screenClass(screen: AppiumScreen, steps: AppiumStep[], ts: boolean, t: (a: string) => string): string {
  const locImport = ts ? `import type { PlatformLocator } from '../utils/locators.js';\n` : '';
  const lines: string[] = [];
  lines.push(
    `// Generated by Swipium. Screen object for ${screen.pageName}${screen.screenSignature ? ` (${screen.screenSignature})` : ''}.`,
  );
  lines.push('// Selectors are centralized here; tests call the action methods below.');
  lines.push(locImport.trimEnd());
  lines.push(`import { BaseScreen } from './BaseScreen.js';`);
  lines.push('');
  lines.push(`export class ${screen.className} extends BaseScreen {`);

  // Locators (centralized).
  for (const el of screen.elements) {
    const durabilityNote = el.durability === 'durable' ? '' : ` // ${el.durability} locator${el.remediation ? ` — ${el.remediation}` : ''}`;
    lines.push(`  readonly ${el.name}${t(': PlatformLocator')} = ${platformLocatorLiteral(el)};${durabilityNote}`);
  }
  lines.push('');

  // Action methods for each (element, action) used in steps on this screen.
  const seen = new Set<string>();
  for (const s of steps) {
    if (s.screen !== screen.className || !s.element) continue;
    const el = screen.elements.find((e) => e.name === s.element);
    if (!el) continue;
    const name = methodName(s.action, s.element);
    if (seen.has(name)) continue;
    seen.add(name);
    if (s.action === 'inputText') {
      lines.push(`  async ${name}(${ts ? 'value: string' : 'value'}) {`);
      lines.push(`    await this.type(this.${s.element}, value);`);
      lines.push('  }');
    } else if (s.action === 'tap') {
      lines.push(`  async ${name}() {`);
      lines.push(`    await this.tap(this.${s.element});`);
      lines.push('  }');
    } else if (s.action === 'scrollTo') {
      lines.push(`  async ${name}() {`);
      lines.push(`    await this.scrollTo(this.${s.element});`);
      lines.push('  }');
    } else if (s.action === 'assertVisible') {
      lines.push(`  async ${name}() {`);
      lines.push(`    await this.assertVisible(this.${s.element});`);
      lines.push('  }');
    }
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function testData(model: AppiumSuiteModel, ts: boolean): string {
  const lines: string[] = [];
  lines.push('// Generated by Swipium. Test data comes from the ENVIRONMENT — secrets are never inlined.');
  lines.push('export const testData = {');
  for (const v of model.variables) {
    lines.push(`  ${varToKey(v)}: process.env.${v} || '',`);
  }
  for (const v of model.secrets) {
    lines.push(`  ${varToKey(v)}: process.env.${v} || '', // secret — provide via environment only`);
  }
  lines.push('};');
  lines.push('');
  if (ts) lines.push('export type TestData = typeof testData;');
  lines.push('');
  return lines.join('\n');
}

function smokeTest(model: AppiumSuiteModel, _ts: boolean): string {
  const classes = [...new Set(model.steps.map((s) => s.screen))];
  const lines: string[] = [];
  lines.push('// Generated by Swipium. Smoke test driving the recorded flow through the screen objects.');
  for (const c of classes) {
    lines.push(`import { ${c} } from '../src/screens/${c}.js';`);
  }
  lines.push(`import { testData } from '../src/data/testData.js';`);
  lines.push('');
  lines.push(`describe('${model.testName} smoke', () => {`);
  // instantiate one screen object per class.
  const inst = new Map<string, string>();
  for (const c of classes) {
    const v = c[0].toLowerCase() + c.slice(1);
    inst.set(c, v);
  }
  lines.push(`  it('completes the recorded flow', async () => {`);
  for (const [c, v] of inst) lines.push(`    const ${v} = new ${c}();`);
  for (const s of model.steps) {
    const v = inst.get(s.screen)!;
    lines.push('    ' + stepCall(v, s));
  }
  lines.push('  });');
  lines.push('});');
  lines.push('');
  return lines.join('\n');
}

function stepCall(screenVar: string, s: AppiumStep): string {
  if (s.element) {
    const name = methodName(s.action, s.element);
    if (s.action === 'inputText') {
      const arg = s.varName ? `testData.${varToKey(s.varName)}` : JSON.stringify(s.text ?? '');
      return `await ${screenVar}.${name}(${arg});`;
    }
    return `await ${screenVar}.${name}();`;
  }
  // No element: generic BaseScreen helpers.
  switch (s.action) {
    case 'tapAt':
      return `await ${screenVar}.tapAt(${s.coords?.[0] ?? 0}, ${s.coords?.[1] ?? 0}); // coordinate fallback — non-release-grade`;
    case 'inputText': {
      const arg = s.varName ? `testData.${varToKey(s.varName)}` : JSON.stringify(s.text ?? '');
      return `await ${screenVar}.type({ android: '' }, ${arg}); // focused-field input`;
    }
    case 'press':
      return `await ${screenVar}.pressKey(${JSON.stringify(s.key ?? 'back')});`;
    case 'swipe':
      return `await ${screenVar}.swipe(${JSON.stringify(s.direction ?? 'up')});`;
    case 'openUrl':
      return `await ${screenVar}.openUrl(${JSON.stringify(s.url ?? '')});`;
    case 'assertVisible':
      return `await ${screenVar}.assertTextVisible(${JSON.stringify(s.text ?? '')});`;
    default:
      return `// unsupported step: ${s.action}`;
  }
}
