// SWIPIUM-REQ-04 — Python Appium emitter. Pure: turns the shared Appium model into a runnable
// Python Appium-Python-Client POM suite (pytest when the project uses it, else unittest). POM
// classes centralize selectors; AppiumBy strategies prefer accessibility id / id; iOS predicate /
// class-chain only where required; XPath is never emitted. Aligns with the Appium Python quickstart.

import type { GeneratedFile } from '../suite/pom.js';
import type { AppiumLocator, AppiumScreen, AppiumStep, AppiumSuiteModel, CrossPlatformElement } from './appiumModel.js';
import type { AutomationProjectProfile } from './projectProfile.js';

export interface PyEmitInput {
  model: AppiumSuiteModel;
  profile: AutomationProjectProfile;
  appId?: string;
  /** pytest | unittest — from the profile. */
  framework: 'pytest' | 'unittest';
}

const DEFAULT_TIMEOUT = 15;

function snake(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase() || 'x';
}

/** Env var (SWIPIUM_TEST_PASSWORD) → a stable test_data key (password). */
export function pyVarToKey(v: string): string {
  const stripped = v.replace(/^SWIPIUM_(TEST_)?/i, '');
  return snake(stripped) || 'value';
}

function pyStr(s: string): string {
  return JSON.stringify(s);
}

/** (AppiumBy.<X>, "<value>") tuple for one Appium locator. No XPath, ever. */
export function appiumByTuple(loc: AppiumLocator): string | undefined {
  switch (loc.strategy) {
    case 'accessibilityId':
      return `(AppiumBy.ACCESSIBILITY_ID, ${pyStr(loc.value)})`;
    case 'id':
      return `(AppiumBy.ID, ${pyStr(loc.value)})`;
    case 'androidUiautomator':
      return `(AppiumBy.ANDROID_UIAUTOMATOR, ${pyStr(`new UiSelector().text("${loc.value.replace(/"/g, '\\"')}")`)})`;
    case 'name':
      return `(AppiumBy.IOS_PREDICATE, ${pyStr(`name == "${loc.value.replace(/"/g, '\\"')}" OR label == "${loc.value.replace(/"/g, '\\"')}"`)})`;
    case 'iosPredicate':
      return `(AppiumBy.IOS_PREDICATE, ${pyStr(loc.value)})`;
    case 'iosClassChain':
      return `(AppiumBy.IOS_CLASS_CHAIN, ${pyStr(loc.value)})`;
    case 'coordinate':
      return undefined;
    default:
      return undefined;
  }
}

function locatorDict(el: CrossPlatformElement): string {
  const parts: string[] = [];
  if (el.android) { const t = appiumByTuple(el.android); if (t) parts.push(`"android": ${t}`); }
  if (el.ios) { const t = appiumByTuple(el.ios); if (t) parts.push(`"ios": ${t}`); }
  if (el.fallback && el.fallback.strategy === 'coordinate') parts.push(`"coordinate": ${pyStr(el.fallback.value)}`);
  else if (el.fallback && !el.android && !el.ios) { const t = appiumByTuple(el.fallback); if (t) parts.push(`"android": ${t}`); }
  return `{${parts.join(', ')}}`;
}

export function emitPythonSuite(input: PyEmitInput): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  files.push({ path: 'requirements.txt', content: requirementsTxt(input) });
  if (input.framework === 'pytest') files.push({ path: 'pytest.ini', content: pytestIni() });
  files.push({ path: 'conftest.py', content: conftest(input) });
  files.push({ path: 'screens/__init__.py', content: '' });
  files.push({ path: 'screens/base_screen.py', content: baseScreen() });
  for (const screen of input.model.screens) {
    files.push({ path: `screens/${snake(screen.className)}.py`, content: screenClass(screen, input.model.steps) });
  }
  files.push({ path: 'data/__init__.py', content: '' });
  files.push({ path: 'data/test_data.py', content: testData(input.model) });
  files.push({ path: 'tests/__init__.py', content: '' });
  files.push({
    path: input.framework === 'pytest' ? 'tests/test_smoke.py' : 'tests/test_smoke.py',
    content: input.framework === 'pytest' ? pytestSmoke(input.model) : unittestSmoke(input.model, input),
  });
  return files;
}

function requirementsTxt(input: PyEmitInput): string {
  const lines = ['# Generated by Swipium — review before committing.', 'Appium-Python-Client>=4.0.0', 'selenium>=4.20.0'];
  if (input.framework === 'pytest') lines.push('pytest>=8.0.0');
  return lines.join('\n') + '\n';
}

function pytestIni(): string {
  return `# Generated by Swipium.
[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra
`;
}

function conftest(input: PyEmitInput): string {
  const appId = input.appId ?? '';
  return `# Generated by Swipium. Appium driver fixture — ALL device/app config is environment-driven.
# Android UiAutomator2 is the default fast-feedback backend; set SWIPIUM_PLATFORM=ios for XCUITest.
import os
import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.options.ios import XCUITestOptions


def build_options():
    platform = os.environ.get("SWIPIUM_PLATFORM", "${input.model.platforms.android ? 'android' : 'ios'}").lower()
    if platform == "ios":
        opts = XCUITestOptions()
        opts.device_name = os.environ.get("IOS_DEVICE_NAME", "iPhone 15")
        bundle_id = os.environ.get("IOS_BUNDLE_ID"${appId ? `, ${pyStr(appId)}` : ''})
        if bundle_id:
            opts.bundle_id = bundle_id
        if os.environ.get("IOS_APP_PATH"):
            opts.app = os.environ["IOS_APP_PATH"]
        if os.environ.get("IOS_UDID"):
            opts.udid = os.environ["IOS_UDID"]
        opts.no_reset = os.environ.get("SWIPIUM_NO_RESET") == "true"
        return opts
    opts = UiAutomator2Options()
    opts.device_name = os.environ.get("ANDROID_DEVICE_NAME", "Android Emulator")
    app_package = os.environ.get("ANDROID_APP_PACKAGE"${appId ? `, ${pyStr(appId)}` : ''})
    if app_package:
        opts.app_package = app_package
    if os.environ.get("ANDROID_APP_ACTIVITY"):
        opts.app_activity = os.environ["ANDROID_APP_ACTIVITY"]
    if os.environ.get("ANDROID_APP_PATH"):
        opts.app = os.environ["ANDROID_APP_PATH"]
    if os.environ.get("ANDROID_UDID"):
        opts.udid = os.environ["ANDROID_UDID"]
    opts.no_reset = os.environ.get("SWIPIUM_NO_RESET") == "true"
    return opts


@pytest.fixture
def driver():
    url = os.environ.get("APPIUM_URL", "http://127.0.0.1:4723")
    drv = webdriver.Remote(url, options=build_options())
    yield drv
    drv.quit()
`;
}

function baseScreen(): string {
  return `# Generated by Swipium. BaseScreen centralizes element interaction so selectors resolve
# per-platform in ONE place and tests never touch raw selectors.
from appium.webdriver.common.appiumby import AppiumBy  # noqa: F401  (used by screen subclasses)
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

DEFAULT_TIMEOUT = ${DEFAULT_TIMEOUT}


class BaseScreen:
    def __init__(self, driver):
        self.driver = driver

    def _spec(self, loc):
        platform = (self.driver.capabilities.get("platformName") or "").lower()
        spec = loc.get("ios") if platform == "ios" else loc.get("android")
        if not spec:
            raise RuntimeError(
                "No durable selector for this platform — element relies on a coordinate fallback "
                "(non-release-grade). Add an accessibility id / resource-id / testID."
            )
        return spec

    def find(self, loc, timeout=DEFAULT_TIMEOUT):
        by, value = self._spec(loc)
        return WebDriverWait(self.driver, timeout).until(
            EC.presence_of_element_located((by, value))
        )

    def tap(self, loc):
        self.find(loc).click()

    def type(self, loc, value):
        el = self.find(loc)
        el.clear()
        el.send_keys(value)

    def scroll_to(self, loc):
        # Best-effort scroll; Appium resolves visibility on find.
        self.find(loc)

    def is_visible(self, loc):
        try:
            return self.find(loc).is_displayed()
        except Exception:
            return False

    def assert_visible(self, loc):
        assert self.find(loc).is_displayed()

    def assert_text_visible(self, text):
        # Non-release-grade text assertion — prefer a structured locator.
        spec = (AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().textContains("%s")' % text)
        assert WebDriverWait(self.driver, DEFAULT_TIMEOUT).until(
            EC.presence_of_element_located(spec)
        ).is_displayed()

    def tap_at(self, x, y):
        # Coordinate tap — brittle, non-release-grade fallback.
        self.driver.tap([(x, y)])

    def press_key(self, key):
        if key == "back":
            self.driver.back()

    def open_url(self, url):
        self.driver.get(url)
`;
}

function methodName(action: AppiumStep['action'], element: string): string {
  const e = snake(element);
  switch (action) {
    case 'tap':
      return `tap_${e}`;
    case 'inputText':
      return `enter_${e}`;
    case 'scrollTo':
      return `scroll_to_${e}`;
    case 'assertVisible':
      return `assert_${e}_visible`;
    default:
      return `act_${e}`;
  }
}

function screenClass(screen: AppiumScreen, steps: AppiumStep[]): string {
  const lines: string[] = [];
  lines.push(`# Generated by Swipium. Screen object for ${screen.pageName}${screen.screenSignature ? ` (${screen.screenSignature})` : ''}.`);
  lines.push('from appium.webdriver.common.appiumby import AppiumBy');
  lines.push('from .base_screen import BaseScreen');
  lines.push('');
  lines.push('');
  lines.push(`class ${screen.className}(BaseScreen):`);
  if (screen.elements.length === 0) lines.push('    pass');
  for (const el of screen.elements) {
    const note = el.durability === 'durable' ? '' : `  # ${el.durability}${el.remediation ? ` — ${el.remediation}` : ''}`;
    lines.push(`    ${snake(el.name)} = ${locatorDict(el)}${note}`);
  }
  if (screen.elements.length) lines.push('');

  const seen = new Set<string>();
  for (const s of steps) {
    if (s.screen !== screen.className || !s.element) continue;
    const el = screen.elements.find((e) => e.name === s.element);
    if (!el) continue;
    const name = methodName(s.action, s.element);
    if (seen.has(name)) continue;
    seen.add(name);
    const attr = snake(s.element);
    if (s.action === 'inputText') {
      lines.push(`    def ${name}(self, value):`);
      lines.push(`        self.type(self.${attr}, value)`);
      lines.push('');
    } else if (s.action === 'tap') {
      lines.push(`    def ${name}(self):`);
      lines.push(`        self.tap(self.${attr})`);
      lines.push('');
    } else if (s.action === 'scrollTo') {
      lines.push(`    def ${name}(self):`);
      lines.push(`        self.scroll_to(self.${attr})`);
      lines.push('');
    } else if (s.action === 'assertVisible') {
      lines.push(`    def ${name}(self):`);
      lines.push(`        self.assert_visible(self.${attr})`);
      lines.push('');
    }
  }
  return lines.join('\n').replace(/\n+$/, '\n');
}

function testData(model: AppiumSuiteModel): string {
  const lines: string[] = [];
  lines.push('# Generated by Swipium. Test data comes from the ENVIRONMENT — secrets are never inlined.');
  lines.push('import os');
  lines.push('');
  lines.push('test_data = {');
  for (const v of model.variables) lines.push(`    ${pyStr(pyVarToKey(v))}: os.environ.get(${pyStr(v)}, ""),`);
  for (const v of model.secrets) lines.push(`    ${pyStr(pyVarToKey(v))}: os.environ.get(${pyStr(v)}, ""),  # secret — environment only`);
  lines.push('}');
  return lines.join('\n') + '\n';
}

function importsForTest(model: AppiumSuiteModel): string[] {
  const classes = [...new Set(model.steps.map((s) => s.screen))];
  return classes.map((c) => `from screens.${snake(c)} import ${c}`);
}

function stepCall(screenVar: string, s: AppiumStep): string {
  if (s.element) {
    const name = methodName(s.action, s.element);
    if (s.action === 'inputText') {
      const arg = s.varName ? `test_data[${pyStr(pyVarToKey(s.varName))}]` : pyStr(s.text ?? '');
      return `${screenVar}.${name}(${arg})`;
    }
    return `${screenVar}.${name}()`;
  }
  switch (s.action) {
    case 'tapAt':
      return `${screenVar}.tap_at(${s.coords?.[0] ?? 0}, ${s.coords?.[1] ?? 0})  # coordinate fallback — non-release-grade`;
    case 'inputText': {
      const arg = s.varName ? `test_data[${pyStr(pyVarToKey(s.varName))}]` : pyStr(s.text ?? '');
      return `${screenVar}.type({"android": (AppiumBy.ACCESSIBILITY_ID, "")}, ${arg})  # focused-field input`;
    }
    case 'press':
      return `${screenVar}.press_key(${pyStr(s.key ?? 'back')})`;
    case 'swipe':
      return `${screenVar}.driver.swipe(0, 0, 0, 0)  # swipe ${s.direction ?? 'up'} — adjust coordinates`;
    case 'openUrl':
      return `${screenVar}.open_url(${pyStr(s.url ?? '')})`;
    case 'assertVisible':
      return `${screenVar}.assert_text_visible(${pyStr(s.text ?? '')})`;
    default:
      return `pass  # unsupported step: ${s.action}`;
  }
}

function instanceVars(model: AppiumSuiteModel): Map<string, string> {
  const classes = [...new Set(model.steps.map((s) => s.screen))];
  const m = new Map<string, string>();
  for (const c of classes) m.set(c, snake(c));
  return m;
}

function pytestSmoke(model: AppiumSuiteModel): string {
  const lines: string[] = [];
  lines.push('# Generated by Swipium. Smoke test driving the recorded flow through the screen objects.');
  lines.push(...importsForTest(model));
  lines.push('from data.test_data import test_data  # noqa: F401');
  const usesFocused = model.steps.some((s) => !s.element && s.action === 'inputText');
  if (usesFocused) lines.push('from appium.webdriver.common.appiumby import AppiumBy  # noqa: F401');
  lines.push('');
  lines.push('');
  lines.push('def test_smoke(driver):');
  const inst = instanceVars(model);
  for (const [c, v] of inst) lines.push(`    ${v} = ${c}(driver)`);
  for (const s of model.steps) lines.push(`    ${stepCall(inst.get(s.screen)!, s)}`);
  return lines.join('\n') + '\n';
}

function unittestSmoke(model: AppiumSuiteModel, input: PyEmitInput): string {
  const lines: string[] = [];
  lines.push('# Generated by Swipium. Smoke test (unittest) driving the recorded flow through screen objects.');
  lines.push('import os');
  lines.push('import unittest');
  lines.push('from appium import webdriver');
  lines.push('from conftest import build_options');
  lines.push(...importsForTest(model));
  lines.push('from data.test_data import test_data  # noqa: F401');
  const usesFocused = model.steps.some((s) => !s.element && s.action === 'inputText');
  if (usesFocused) lines.push('from appium.webdriver.common.appiumby import AppiumBy  # noqa: F401');
  lines.push('');
  lines.push('');
  lines.push('class SmokeTest(unittest.TestCase):');
  lines.push('    def setUp(self):');
  lines.push('        url = os.environ.get("APPIUM_URL", "http://127.0.0.1:4723")');
  lines.push('        self.driver = webdriver.Remote(url, options=build_options())');
  lines.push('');
  lines.push('    def tearDown(self):');
  lines.push('        if self.driver:');
  lines.push('            self.driver.quit()');
  lines.push('');
  lines.push('    def test_smoke(self):');
  const inst = instanceVars(model);
  for (const [c, v] of inst) lines.push(`        ${v} = ${c}(self.driver)`);
  for (const s of model.steps) lines.push(`        ${stepCall(inst.get(s.screen)!, s)}`);
  lines.push('');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push('    unittest.main()');
  return lines.join('\n') + '\n';
}
