// SWIPIUM-REQ-04 — README emitter. Pure: documents the generated suite, the required environment
// variables (app id/path, device, Appium host/port, credentials, test data), and the exact run
// commands. Honest about platform coverage and non-release-grade fallbacks.

import type { AppiumSuiteModel } from './appiumModel.js';
import type { AutomationProjectProfile } from './projectProfile.js';

export interface ReadmeInput {
  model: AppiumSuiteModel;
  profile: AutomationProjectProfile;
  language: 'typescript' | 'javascript' | 'python';
  appId?: string;
  outputDir: string; // relative path where the suite was written, e.g. .swipium/automation/js
}

function envTable(model: AppiumSuiteModel, isPython: boolean): string[] {
  const common = [
    '| `APPIUM_HOST` / `APPIUM_PORT`' + (isPython ? ' / `APPIUM_URL`' : '') + ' | Appium server location (default 127.0.0.1:4723) |',
    '| `SWIPIUM_PLATFORM` | `android` (default) or `ios` |',
    '| `ANDROID_DEVICE_NAME`, `ANDROID_APP_PACKAGE`, `ANDROID_APP_ACTIVITY`, `ANDROID_APP_PATH`, `ANDROID_UDID` | Android target/app |',
    '| `IOS_DEVICE_NAME`, `IOS_BUNDLE_ID`, `IOS_APP_PATH`, `IOS_UDID` | iOS target/app (when SWIPIUM_PLATFORM=ios) |',
  ];
  const data = model.variables.map((v) => `| \`${v}\` | test data (non-secret) |`);
  const secrets = model.secrets.map((v) => `| \`${v}\` | **secret** — provide via environment/CI secrets only |`);
  return ['| Variable | Purpose |', '| --- | --- |', ...common, ...data, ...secrets];
}

export function emitReadme(input: ReadmeInput): string {
  const isPython = input.language === 'python';
  const { profile, model } = input;
  const platformCoverage: string[] = [];
  if (model.platforms.android) platformCoverage.push(`Android (${profile.platforms.android.level})`);
  if (model.platforms.ios) platformCoverage.push(`iOS (${profile.platforms.ios.level})`);

  const runCmd = isPython
    ? profile.testFramework === 'pytest'
      ? '```sh\npip install -r requirements.txt\nappium &   # start a local Appium server\npytest\n```'
      : '```sh\npip install -r requirements.txt\nappium &   # start a local Appium server\npython -m unittest discover -s tests\n```'
    : '```sh\nnpm install\nnpx appium &   # or rely on the @wdio/appium-service\nnpm test\n```';

  const brittle = model.audit.brittle;
  const lines: string[] = [];
  lines.push(`# ${input.appId ?? 'App'} — Appium ${isPython ? 'Python' : 'WebdriverIO'} POM suite`);
  lines.push('');
  lines.push('> Generated by Swipium from recorded QA actions. **Review before committing.**');
  lines.push('');
  lines.push('## What this is');
  lines.push('');
  lines.push(`A Page/Screen Object Model Appium suite (${input.language}). Selectors live in screen objects; tests call action methods only.`);
  lines.push('');
  lines.push(`- **Language:** ${input.language}`);
  lines.push(`- **Runner:** ${profile.testFramework}`);
  lines.push(`- **Default backend:** ${profile.defaultBackend}${profile.secondaryBackend ? ` (secondary: ${profile.secondaryBackend})` : ''}`);
  lines.push(`- **Platform coverage in this suite:** ${platformCoverage.join(', ') || 'none detected'}`);
  lines.push(`- **Screens:** ${model.screens.map((s) => s.className).join(', ') || 'none'}`);
  lines.push('');
  lines.push('## Run');
  lines.push('');
  lines.push(runCmd);
  lines.push('');
  lines.push('## Environment variables');
  lines.push('');
  lines.push(...envTable(model, isPython));
  lines.push('');
  lines.push('## Locator readiness');
  lines.push('');
  lines.push(`Locator durability: ${model.audit.durable} durable / ${model.audit.semi} semi / ${brittle} brittle (${model.audit.brittlePct}% brittle).`);
  if (brittle > 0) {
    lines.push('');
    lines.push(`⚠ ${brittle} brittle/coordinate locator(s) are marked non-release-grade in the screen objects. Add a durable accessibility id / resource-id / testID before gating CI on this suite.`);
  }
  lines.push('');
  lines.push('## Honest coverage note');
  lines.push('');
  lines.push('iOS selectors/capabilities are emitted from app-map evidence where available, but iOS coverage is NOT proven unless the suite was actually run on iOS. XPath is never generated.');
  lines.push('');
  return lines.join('\n');
}
